name: Golang build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Go
      uses: actions/setup-go@v2
      with: 
        go-version: '1.14.0'

    - name: Run build
      run: go build "./cmd"

    - name: Run vet & lint
      run: |
        go vet "./cmd"
        golint "./cmd"

    - name: Run testing
      run: cd test && go test -v
      