name: Golang build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Go
      uses: actions/setup-go@v2
      with: 
        go-version: '1.14.0'

    - name: Run build
      run: go build ./cmd/main.go

    - name: Run vet
      run: go vet "./cmd"
    
    - name: Run golangci-lint
      uses: actions-contrib/golangci-lint@v1

    - name: Run testing
      run: cd test && go test -v
      